### ISSUE TITLE
what happened to ps4eop

### ISSUE THREAD

**Issue by gs-soda** [MystifyCodes/PS3-Projects#1]
i was generally expecting a ps4 emulator but then you decided to remove your twitter and ban everyone from servers AND delete the emu files. respect lost man.

**Comment by MystifyCodes** [comment]
> i was generally expecting a ps4 emulator but then you decided to remove your twitter and ban everyone from servers AND delete the emu files. respect lost man.

ah sorry my accounts were hacked for 3 days it was someone from india trying to scam people
